stages:
  - sync-code
  - build
  - deploy

sync-code:
  stage: sync-code
  only:
    - master
  script:
    - bash push-remote-git-repos.sh
  tags:
    - qiushaocloud-runner

build:
  stage: build
  only:
    - master
  script:
    - docker build -t qiushaocloud/git-server-docker:latest .
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/git-server-docker:latest
  tags:
    - qiushaocloud-runner
